name: Sync work‑log from Google Sheets
on:
  schedule:           # co 5 min; zmień według potrzeb
    - cron:  '*/5 * * * *'
  workflow_dispatch:  # oraz ręczne uruchomienie

jobs:
  pull‑csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pobierz CSV z Sheets
        run: |
          curl -L "https://opensheet.elk.sh/1xWztAqAJurUBzUcfxg6I4AIuuQa-BKyOE8k34ARD7oc/Liczba%20odpowiedzi%3A%201?format=csv" \
          > data/$(date '+%Y-%m-%d').csv

      - name: Commit & push
        run: |
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git add data/*.csv
          git commit -m "Auto‑backup work‑log $(date --iso-8601=seconds)" || echo "Nothing to commit"
          git push
